modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory
credits="TallestEgg" #optional
authors="TallestEgg" #optional

[[mods]] #mandatory
modId="guardvillagers" #mandatory
version="1.0" #mandatory
displayName="Guard Villagers" #mandatory
description='''
This mod adds guard villagers.
'''

[[dependencies.guardvillagers]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[28,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.guardvillagers]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"